### ISSUE TITLE
Wrong encoding on windows?

### ISSUE THREAD

**Issue by ChrisOKay** [koxudaxi/ruff-pycharm-plugin#123]
**Describe the bug**
When using the plugin with 'reformat code', UTF-8 characters wrongly get decoded with windows-1250.

**To Reproduce**
1. place UTF8 character in module, e.g. →
2. Run reformat code (ctrl+alt+L)
3. Character gets changed to â†’ (i.e. the bytestring b'\xe2\x86\x92' gets decoded with windows-1250 instead of utf-8)

**Expected behavior**
Document should remain utf-8 encoded

**Screenshots**
![ruff_encode_error](https://user-images.githubusercontent.com/22896985/224992289-befb6473-e713-4df9-81bf-683d0a5d33dd.gif)

**Environments (please complete the following information):**
 - IDE: PyCharm Community 2022.3.3
 - OS: Windows 10
 - Ruff Version 0.0.254
 - Plugin version 0.0.9 & 0.0.10

**Additional information**
Directly applying `ruff check module.py` on the document does not change the encoding.
Disabling the "Run ruff when reformat code" option stops this behaviour.

**Comment by KotlinIsland** [comment]
I think this is a highly critical bug that makes the plugin completely unusable on Windows.

**Comment by lilaboc** [comment]
Could you please release this to marketplace? I think I bumped into this bug also

**Comment by koxudaxi** [comment]
@lilaboc 
I tried to publish it to the market.
but it failed. I will fix the problem soon.
https://github.com/koxudaxi/ruff-pycharm-plugin/actions/runs/4739238071

**Comment by koxudaxi** [comment]
@lilaboc @ChrisOKay  @KotlinIsland 
I just published it !!
https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/322790

**Comment by KotlinIsland** [comment]
> JetBrains is reviewing this update. Please expect it to be approved within two business days of the upload.

Great

**Comment by lilaboc** [comment]
Manually installed and it's working fine now. Thanks guys!
