### ISSUE TITLE
Can't undo ruff autoformat (or ruff check --fix on 'save file')

### ISSUE THREAD

**Issue by glarione** [koxudaxi/ruff-pycharm-plugin#126]
**Describe the bug**
When I make some fixes to code and if settings like on picture, if I want to undo 

**To Reproduce**
1. Go to some file and add a few empty rows (for example).
2. Push Ctrl+Alt+L (or save file if this setting is checked).
3. Write some text.
4. Try to undo changes till before p.1.

**Expected behavior**
I can undo fixes by Ruff.

**Screenshots**
![image](https://user-images.githubusercontent.com/61240531/227789506-0a7847a4-dd92-4895-8b7c-d423bd4e4b3f.png)

![image](https://user-images.githubusercontent.com/61240531/227789554-350f9e87-5bee-4ff7-bd33-3995e99f3960.png)

**Environments (please complete the following information):**
 - IDE: [PyCharm Community 2022.3.1]
 - OS: [Fedora Linux 37]
 - Ruff Version [0.0.259]
 - Plugin version [ 0.0.10 ]

**Comment by metoikos** [comment]
+1 for this. I had no choice but to disable the plugin. But I don't know how could it be fixed? 
It's literally an external process that edits the file out of the editor's scope. So, the fix should come from JetBrains probably.

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
I just confirmed the problem!!

> So, the fix should come from JetBrains probably.
Why do you think this?

I tested `undo` action before releasing the plugin. It works fine.
JetBrains may change the behavior :thinking:

**Comment by cfxegbert** [comment]
We need a setting to turn off the "--fix" option for the plugin.  Typically I'm going to run ruff on the command line if I'm going to use --fix.  In my case rule F401 kept on removing unused imports whenever the editor was saving the file.  This is a unit testing file and one of the tests was just importing the library.  I ended up having to do a  "# ruff: noqa: F401" in the file while I was writing it.

**Comment by metoikos** [comment]
> So, the fix should come from JetBrains probably.

So, an external binary/process changes the file's contents, and the problem seems like a sync issue (my theory 😅). Second, I searched the internet, and similar plugins (with external formatter, etc.) had the same problem.

And +1 for the `--fix`. Sometimes it's really, let's say, not annoying, but it's tiresome that the editor removes the imports immediately (this is not a complaint) :)

Thank you for the plugin and the support you show.

**Comment by jankatins** [comment]
Für disabling specific rules during --fix: https://github.com/koxudaxi/ruff-pycharm-plugin/issues/135

**Comment by koxudaxi** [comment]
@cfxegbert @metoikos  
It's a good point. I don't reformat before using a new variable and imported module :sweat_smile: 
@jankatins 
I checked your issue.
How do we set up the rules to ignore specific actions? Would you be able to use setting preference or project toml? :thinking:

**Comment by koxudaxi** [comment]
@glarione @metoikos 
Would you happen to know how to reproduce the problem?
I tried the steps. But I can't reproduce it. :(
> To Reproduce
> Steps to reproduce the behavior:

> Go to some file and add a few empty rows (for example).
> Push Ctrl+Alt+L (or save file if this setting is checked).
> Write some text.
> Try to undo changes till before p.1.

**Comment by cfxegbert** [comment]
To reproduce for me.

Make sure you have the "F" rules enabled (pyflakes)
```python
def some_function() -> None:
  import re
```
Wait a few seconds for the file to be saved automatically.  You will end up with
```python
def some_function() -> None:
  pass
```

**Comment by jankatins** [comment]
@koxudaxi specifying some rules in the config and then calling ruff with e.g. ` --unfixable F841,F401` to overwrite anything in any config file.

**Comment by cfxegbert** [comment]
If we have an option to turn off fix by default could we have a "Ruff fix" menu item under the Tools menu?

**Comment by koxudaxi** [comment]
@jankatins 
Nice. I will implement it.

**Comment by koxudaxi** [comment]
@cfxegbert 
Thank you for providing the example.
But, I can't reproduce my machine. :(
IDE: [PyCharm 2023.1]
OS: [macOS 12.5]
Ruff Version [0.0.254]
Plugin version [ 0.0.10 ]

> If we have an option to turn off fix by default could we have a "Ruff fix" menu item under the Tools menu?

we have `ruff action`. we can add a shortcut.
Does this satisfy your request? 
<img width="992" alt="image" src="https://user-images.githubusercontent.com/630670/232945169-ce026169-ae5e-4b67-a8dd-491cfa1dac88.png">

**Comment by cfxegbert** [comment]
> @cfxegbert Thank you for providing the example. But, I can't reproduce my machine. :( IDE: [PyCharm 2023.1] OS: [macOS 12.5] Ruff Version [0.0.254] Plugin version [ 0.0.10 ]

I'm using Ruff Version [0.0.261]
I also had `Run ruff when the python file is saved` enabled

**Comment by koxudaxi** [comment]
@cfxegbert 
I can't reproduce the problem in debug mode in IntelliJ IDEA. 
But, I met the error in PyCharm with the GitHub copilot plugin.
Do you use Copliot or another plugin to change code?

**Comment by cfxegbert** [comment]
I do not use Copilot.  I have several internal work plugins.  I have disabled those plugins and it still reformats.

**Comment by koxudaxi** [comment]
I believe this issue has been resolved as we've changed the method of running ruff on save to use the `actionOnSave` API. If you encounter any problems, please reopen the issue.
