### ISSUE TITLE
Shows available modules as undefined in debug console

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/ruff-pycharm-plugin#132]
**Describe the bug**
Although a module is imported in the source code, it is shown as unavailable in the debug console

**To Reproduce**
```py

import json


def test_():
    # Put breakpoint on next statement
    assert True

```

1. Run test in debug mode
2. On break, go to debug console and type `json.loads()`
3. See warning

<img width="197" alt="Screenshot 2023-04-05 at 12 59 10" src="https://user-images.githubusercontent.com/7534547/230061447-6058c5a6-e4c1-4e42-8755-b99dd65b941d.png">

**Expected behavior**
The `json` module has been loaded previously and there should not be a warning

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2023.1
 - OS: macOS 13.2.1
 - Ruff Version 0.0.260
 - Plugin version: 0.0.10

**Additional context**

**Comment by koxudaxi** [comment]
@chbndrhnns 
I'm sorry for my late response.
Does the problem come from ruff plugin?
The plugin doesn't affect the debug console.

**Comment by koxudaxi** [comment]
Closed temporarily due to lack of response.
Please comment again if you have any questions.
