### ISSUE TITLE
(🎁) Add icon for plugin

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#136]
This plugin is very good, but the lack of an icon is misleading. ☹️  

![image](https://user-images.githubusercontent.com/65446343/231961276-d8e21b9d-5f97-4061-8f00-23bb14ddb1fa.png)

**Comment by johnthagen** [comment]
It seems like using Ruff's offical lightning bolt icon would be most appropriate?

For example, here is it's badge:

```
[![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v1.json)](https://github.com/charliermarsh/ruff)
```

[![Ruff](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/charliermarsh/ruff/main/assets/badge/v1.json)](https://github.com/charliermarsh/ruff)

**Comment by johnthagen** [comment]
Here is the full SVG that is used in Ruff's Mkdocs project:

- https://github.com/charliermarsh/ruff/blob/main/docs/assets/ruff.svg
