### ISSUE TITLE
(🐞) Inspections aren't appearing

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#142]
**Describe the bug**
No ruff inspections are appearing in PyCharm

**To Reproduce**
```py
class A:
    def __init__(self):
        pass


def foo():
    """doc string"""
    f"hello!"
```

```toml
[tool.ruff]
extend-select = ["I", "UP", "PYI", "ANN"]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/65446343/232986869-74bd8993-4cc9-4515-90b3-d2662659a5b0.png)

![image](https://user-images.githubusercontent.com/65446343/232987231-341297d1-0049-4c8e-ae6d-ca2e715b2f6c.png)

**Environments (please complete the following information):**
 - IDE: [e.g. PyCharm Community 2022.1 ] PC 2023.1.1 RC
 - OS: [e.g. macOS  12.2.0 ] Windows 10
 - Ruff Version [e.g. 1.9.0 ] 0.0.261
 - Plugin version [e.g. 0.3.11 ] 0.0.11

**Comment by koxudaxi** [comment]
@KotlinIsland 
I just confirmed the problem.
The newest ruff changed the result json structure.
I will create the PR.

**Comment by pr1ntr** [comment]
Any word on when this will hit marketplace? :)

**Comment by KotlinIsland** [comment]
@koxudaxi Should this issue be closed?

**Comment by koxudaxi** [comment]
@pr1ntr 
> The review may take up to two business days (Monday - Friday, CET timezone, excluding official holidays). 

https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/323102
you can download it from here.

**Comment by koxudaxi** [comment]
@KotlinIsland 
> This issue would resolve the problem.

It's Interesting!! I have not heard about the format.

**Comment by KotlinIsland** [comment]
Qodana uses it for it's baseline

**Comment by koxudaxi** [comment]
I just understood the format is for the results of linting tools.
Thank you!!
