### ISSUE TITLE
TODO lines removed

### ISSUE THREAD

**Issue by tzmara** [koxudaxi/ruff-pycharm-plugin#143]
**Describe the bug**
When activated ruff plugin deletes lines containing `# todo: ....` while ruff without plugin doesn't. I'm pretty sure it's a plugin problem, but I created an issue [here](https://github.com/PyCQA/pyflakes/issues/770) as well. 

**To Reproduce**
1. Have `F` in `pyproject.toml` in `fixable`
2. Have first 3 options in ruff plugin settings enabled
3. Add a comment with `# todo: asdf asdf` 
4. save -> comment is gone

**Expected behavior**
- comment not gone

**Screenshots**
Not applicable

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2023.1 
 - OS: linux
 - Ruff Version: 0.0.261
 - Plugin version: 0.0.11

**Additional context**
I would be totally fine to have the rule which gets applied. In F on ruffs documentation I didn't find a todo/fixme rule?

**Comment by koxudaxi** [comment]
@tzmara 
the plugin runs the ruff command in the project root directory.
Do you define the rules in the file like pyprojec.toml?

**Comment by koxudaxi** [comment]
レスポンスがないため一旦クローズします。
なにかあれば再度コメントお願いします。
