### ISSUE TITLE
(🎁) Add a "suppress" quick fix

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#147]
```py
from typing import Callable  # UP035 Import from `collections.abc` instead: `Callable` 

a: Callable
```

expected:
```py
from typing import Callable  # noqa: UP035

a: Callable
```

It would be great if the plugin could automatically suppress an inspection from ruff.

**Comment by koxudaxi** [comment]
@KotlinIsland 
Thank you for providing a good idea :smile: 
OK, I will add it.

**Comment by jankatins** [comment]
Would be nice to also add the explanation as a comment, e.g. `# noqa: UP035 Import from 'collections.abc' instead: 'Callable'`, so one actually has a chance to see why the noqa was added...

**Comment by KotlinIsland** [comment]
> Would be nice to also add the explanation as a comment, e.g. `# noqa: UP035 Import from 'collections.abc' instead: 'Callable'`, so one actually has a chance to see why the noqa was added...

What if the plugin displayed that information as in inlay hint instead?

**Comment by jankatins** [comment]
That would be even more awesome. Is that possible that it recognizes "noqa: label" and diaplays the explanation?

**Comment by KotlinIsland** [comment]
Hmmm, I don't think it's actually do-able, it wouldn't be able to query ruff to find out what the message should be.

**Comment by jankatins** [comment]
If ruff is the only problem, I can ask in there if there is a way to do that? I would guess one only needs to query the Ids once?

E.g. `ruff explain <label>`?

**Comment by jankatins** [comment]
Asked in the ruff repo: https://github.com/charliermarsh/ruff/issues/4343
