### ISSUE TITLE
(🐞) The ruff inspections can cause considerable user input lag

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#148]
**Describe the bug**
Because ruff runs as the user is typing, it will hang the thread while it's waiting for ruff to run, causing the UI to freeze momentarily. This lag unfortunately makes the inspections non-viable for me 😢

I am not very familiar with the intellij API, but I wonder if it's possible to initiate ruff in a background thread:
- When the user pauses typing, start ruff in a background thread
- if the user starts typing again before ruff finishes, then cancel the current ruff
- only add the inspections when ruff returns before the user starts typing again

**To Reproduce**
1. enable the inspection
2. type anything into the IDE

**Expected behavior**
no lag

**Environments (please complete the following information):**
 - IDE: [e.g. PyCharm Community 2022.1 ]  2023.1.1
 - OS: [e.g. macOS  12.2.0 ]  Windows 10
 - Ruff Version [e.g. 1.9.0 ]  0.0.262
 - Plugin version [e.g. 0.3.11 ]  0.0.12

**Additional context**
I am within a corporate environment, and processes have a 'start up lag' due to some kind of security tooling.

**Comment by koxudaxi** [comment]
@KotlinIsland 
Thank you for raising the issue.
I don't feel the lag.
My machines are an i7-12700H laptop and m1 Mac mini :sweat_smile: 

> I am within a corporate environment, and processes have a 'start up lag' due to some kind of security tooling.
Interesting!!  
OK, I will check the JetBrains API.

**Comment by koxudaxi** [comment]
> , I am not very familiar with the intellij API, but I wonder if it's possible to initiate ruff in a background thread:

The plugin calls Ruff in another thread.
But, the method blocks the thread to show the inspection.

I think the plugin can stop running the ruff process when starting the next inspection by the user input.

**Comment by KotlinIsland** [comment]
> But, the method blocks the thread to show the inspection.

There are no inspections in my example

> The plugin calls Ruff in another thread.

Are you sure? I replaced the ruff executable with this Kotlin native executable:
```kt
import platform.posix.sleep

fun main() {
    sleep(10)
}
```

Now everytime I type into PyCharm the UI freezes for 10 seconds.

**Comment by koxudaxi** [comment]
Short answer, PyCharm calls the inspection method of this plugin sequential and synchronous.

> Now every time I type into PyCharm the UI freezes for 10 seconds.

I'm sorry, my explanation is not unclear.
The plugin calls ruff commands in the thread pool. But, sync the command result.It's blocking and It is not async.

Last night, I was checking behavior.
The plugin calls ruff command every about 1 sec while inputting something in the code.

**Comment by KotlinIsland** [comment]
@koxudaxi Ahh, I see, here is the issue

https://github.com/koxudaxi/ruff-pycharm-plugin/blob/bb1cf1baeeaf15bc30f2016cfc84eb9e58d656fc/src/com/koxudaxi/ruff/Ruff.kt#L204

What is happening here is that ruff is being run on another thread, but the main thread is just waiting for the other thread to finish, completely defeating the point of running on another thread.

**Comment by koxudaxi** [comment]
@KotlinIsland 
Yes. also we run the methods in ReadAction.
We should check the APIs.

I tried the method to wrap the inspection method.
But, it's hang :(
https://github.com/JetBrains/intellij-community/blob/0c9080a4ecdf96bb6b089cb6761e2a7a943717a2/platform/core-api/src/com/intellij/openapi/application/ReadAction.java#L98

I just found the document :eyes: 
https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html#do-not-perform-long-operations-in-ui-thread

**Comment by KotlinIsland** [comment]
What about something like this https://github.com/KotlinIsland/ruff-pycharm-plugin/tree/fix/async

**Comment by koxudaxi** [comment]
I will try it when I arrive at office. 
Thank you

**Comment by KotlinIsland** [comment]
It's a concept only, it's likely that it won't work "out of the box"

**Comment by koxudaxi** [comment]
I tried your concept. But, we need to run the action in the ReadAction.
And I changed the implementation to that is run asynchronously. 
But, PyCharm doesn't show the inspection highlights if the ruff command spent a lot of time.
Because the inspection method is finished before adding the inspection highlights of ruff to the highlights list.

I show the steps
1. PyCharm calls inspection methods include ruff inspection method
2. Ruff inspection method invokes the Ruff command asynchronously.
3. PyCharm do highlighting code by using the result list of the inspection methods
4. Ruff inspection method gets a result from the Ruff command 
5. Ruff inspection method adds the result to the result list.  <- The result has never been used. Because the highlighting action had already finished by PyCharm.

**Comment by KotlinIsland** [comment]
@hsz Do you have time to take a quick look at this?

Basically we want to run a linter as the user is typing, that will add inspections into the active editor, but we do not want to block the UI thread. What would be the suggested API/pattern for a case like this?

**Comment by KotlinIsland** [comment]
https://intellij-support.jetbrains.com/hc/en-us/community/posts/11275128092690-What-is-the-suggested-pattern-for-implementing-a-plugin-that-runs-an-external-command-that-generates-inspections-

**Comment by johnthagen** [comment]
Maybe a bit of a crazy idea, but does the IntelliJ platform support the LSP protocol? Since the LSP protocol is specifically designed for this, maybe it could help?

Then we could use:

- https://github.com/charliermarsh/ruff-lsp

**Comment by KotlinIsland** [comment]
Lol, they would rather rewrite the scala compiler from scratch than support LSP. I think Fleet does though.

**Comment by KotlinIsland** [comment]
This is resolved in 0.0.14

**Comment by johnthagen** [comment]
> This is resolved in 0.0.14

I can try enabling the plugin again 😆
