### ISSUE TITLE
Import sort order doesn't match ruff cli

### ISSUE THREAD

**Issue by atom-andrew** [koxudaxi/ruff-pycharm-plugin#150]
**Describe the bug**
Thanks for this plugin.  I'd like to use it but I've had to disable it because it doesn't sort the same way ruff does, which breaks our pre-commit and CI flows.  It appears to sort first-party imports differently, among other things.  An example is at https://github.com/atom-andrew/pycharm-ruff-test/blob/main/pycharm_ruff_test/test_bar.py:
```
import time

import pytest
from pycharm_ruff_test.bar import BAR  # there should be a blank line above this


@pytest.autouse('foo')
def test_foo():
    time.sleep(0.1)
    print(BAR)
```

**To Reproduce**
1. Open https://github.com/atom-andrew/pycharm-ruff-test/ in pycharm 
2. Open `pycharm_ruff_test/test_foo.py`
3. Trigger a reformat with the ruff plugin (nothing should happen)
4. Run `ruff --fix .` at the top-level of the repo and a line should be added.

**Expected behavior**
This plugin and ruff

**Screenshots**
Also, gif movies are recommended.

**Environments (please complete the following information):**
MacOS
PyCharm 2022.3.3 (Professional Edition)
Build #PY-223.8836.43, built on March 10, 2023
plugin version 0.0.10

**Additional context**
Instead of using the plugin, I've just added `ruff --fix-only --exit-zero $FilePath$` as a filewatcher, but I'd rather just have an easy to configure plugin.

**Comment by koxudaxi** [comment]
@atom-andrew 
Thank you for creating the issue.
It works fine in my environment :thinking: 

[Screencast from 2023年04月21日 00時02分56秒.webm](https://user-images.githubusercontent.com/630670/233407506-77f19206-6944-46b7-9322-4ec950667907.webm)

```bash
$  /home/koudai/.local/bin/ruff --version
ruff 0.0.247
```
What ruff version is used?
![image](https://user-images.githubusercontent.com/630670/233408754-09fac08d-574c-4a2b-9c4d-7562dc5cc5e3.png)

**Comment by atom-andrew** [comment]
I was using 0.0.261

**Comment by atom-andrew** [comment]
I also was running it as a per-project version  (installed via conda, if that matters)

**Comment by koxudaxi** [comment]
I tried to run with `0.0.261`
It works fine.
![image](https://user-images.githubusercontent.com/630670/233426985-a6108a22-1587-4320-bb69-4033e26539e0.png)

**Comment by koxudaxi** [comment]
> I also was running it as a per-project version (installed via conda, if that matters)

OK, I should try `conda` to install ruff.

**Comment by atom-andrew** [comment]
Ok, so it's more complicated than I thought.  I've been having the problem on Save.  When I enable "Run ruff when Reformat Code", and reformat a region it does insert the line above the first-party import.  Then when I save it, it goes back to not having a line above it.

**Comment by koxudaxi** [comment]
Interesting.
you mean the behavior changes between `Reformat` and `SaveOn` :thinking: 

The plugin calls the ruff command in the project root directory.
with these arguments"--exit-zero", "--no-cache", "--fix"`

**Comment by atom-andrew** [comment]
Here's an interesting datapoint.  This problem persists even if I disable "Run ruff when python file is saved".  When I do that, I know longer see the "Running Ruff" message in the IDE footer.  However, the problem goes away when I disable the plugin entirely.

**Comment by atom-andrew** [comment]
I have an even more interesting data point:  This problem only happens if I have a second project open with the  "Run ruff when python file is saved" enabled for the second proejct.  These projects are not nested.  This suggests to me (1) ruff is bring triggered on save for files outside the project, and (2) it is not picking up the right settings so the formatting is wrong (presumably it can't guess what the first-party path is).

**Comment by koxudaxi** [comment]
I just reproduced the problem when  I opened the file from another project window.
I will disable the SaveOn option for other projects by default.
