### ISSUE TITLE
Ruff executable not found with conda env 

### ISSUE THREAD

**Issue by LLejoly** [koxudaxi/ruff-pycharm-plugin#166]
**Describe the bug**
(Tested on Windows 11)
Ruff plugin does not recognize the ruff executable when ruff is installed in a conda environment.

message `Ruff executable not found`

**To Reproduce**
1. install conda virtual env
2. specify the path the ruff executable ...\Script\ruff.exe

**Expected behavior**
The ruff executable should be found.

**Environments (please complete the following information):**
 - IDE: [e.g. PyCharm Community 2023.1 ]
 - OS: [e.g. windows 11 ]
 - Ruff Version [e.g. 0.0265 ]
 - Plugin version [e.g. 0.0.13 ]

**Comment by koxudaxi** [comment]
@LLejoly 
I have released the new version as `0.0.15`!!
