### ISSUE TITLE
Add inlay hint for `noqa: <code>` 

### ISSUE THREAD

**Issue by jankatins** [koxudaxi/ruff-pycharm-plugin#168]
in https://github.com/koxudaxi/ruff-pycharm-plugin/issues/147 it was suggested that it is possible to add an inlay hint to the code of `# noqa: <code>` so the user can see what the code actually means.

For the info: `ruff rule S101 --format=json` shows this:

```
ruff rule S101 --format=json
{
  "code": "S101",
  "linter": "flake8-bandit",
  "summary": "Use of `assert` detected"
}
```

There is currently a PR to even add the full explanation: https://github.com/charliermarsh/ruff/pull/4367. So querying ruff is taken care of :-) Not idea if jetbrains has an api to recognize and add something to the code, though.

**Comment by charliermarsh** [comment]
We do this in the Ruff LSP via the LSP's hover action. If we see a `noqa` code, then we surface the rule explanation in the tooltip. (I'm not super familiar with PyCharm's API, this is just for context.) You can find the code [here](https://github.com/charliermarsh/ruff-lsp/blob/376e009b20677f1b9bdeda4b62d6cd054e31f867/ruff_lsp/server.py#L252).

Note that you don't actually need https://github.com/charliermarsh/ruff/pull/4367 to support this. You can just take the content of `ruff rule S101`, which renders Markdown, and use that in the tooltip -- at least in the LSP protocol.
