### ISSUE TITLE
global find/replace immediately rolled back by plugin

### ISSUE THREAD

**Issue by ashanbrown** [koxudaxi/ruff-pycharm-plugin#169]
**Describe the bug**
When I do a global find/replace, the ruff plugin rolls immediately rolls back my changes when set to run on save.

**To Reproduce**
1. Enable ruff plugin.
2. Do a global find/replace on anything
3. See the changes immediately rolled back by ruff.
4. Disable ruff plugin and confirm that global find/replace does actually work.

**Expected behavior**
Ruff shouldn't roll back find/replace.

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2023.1
 - OS: macos
 - Ruff Version 0.0.262
 - Plugin version 0.0.14

**Additional context**
Settings:
<img width="730" alt="image" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/1858046/9d5d8244-22e2-40a4-8caf-aab090ee4441">

**Comment by koxudaxi** [comment]
@ashanbrown 
I have released the new version as `0.0.15`!!

**Comment by atom-andrew** [comment]
I've tried the new version (0.0.15) and as far as I can tell it behaves the same way.  My global find replace is immediately rolled back.
