### ISSUE TITLE
Ruff plugin to IntelliJ: Formatting changes self.assertEqual(expected, actual) to assert expected == actual

### ISSUE THREAD

**Issue by clarosoft** [koxudaxi/ruff-pycharm-plugin#238]
**Describe the bug**
Whenever I reformat code using Ctrl-Alt-L the above changes are made, which is not the pytest recommended syntax. I am running python 3.9, pytest 7.4.0 and Ruff Plugin 0.0.19. I sent this to IntelliJ and they asked me to disable all plugins and try again. Through a process of elimination I worked out Ruff plug in was causing the issue.

**To Reproduce**
In IntelliJ select the following code:
```

```
    @patch("shopify.Product.get")
    @patch("shopify.Product.find")
    def test_product_not_bundle_created(self, mock_product_find, mock_product_get):
        self.validated_kylie_unbundled_product_event.topic_name = "product/create"

        mock_product = shopify.Product()
        mock_product.product_type = ""
        mock_product.variants = []
        mock_product_find.return_value = mock_product

        expected = {"errors": [],
                    "info": [{"INFO": "Product is not a bundle", "product_id": 7843563208946}],
                    "id": 7843563208946,
                    "webhook": "products_webhook.py"}
        actual = products_webhook._do_work(self.validated_kylie_unbundled_product_event)
        self.assertEqual(expected, actual)
```
```
Reformat the selected code through Ctrl-Alt-L

**Expected behavior**
No change should be made to the code, but instead the last assert statement is changed:

```
    @patch("shopify.Product.get")
    @patch("shopify.Product.find")
    def test_product_not_bundle_created(self, mock_product_find, mock_product_get):
        self.validated_kylie_unbundled_product_event.topic_name = "product/create"

        mock_product = shopify.Product()
        mock_product.product_type = ""
        mock_product.variants = []
        mock_product_find.return_value = mock_product

        expected = {"errors": [],
                    "info": [{"INFO": "Product is not a bundle", "product_id": 7843563208946}],
                    "id": 7843563208946,
                    "webhook": "products_webhook.py"}
        actual = products_webhook._do_work(self.validated_kylie_unbundled_product_event)
        assert actual == expected
```

**Screenshots**
Also, gif movies are recommended.

**Environments (please complete the following information):**
 - IDE: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
 - OS: Ubuntu 22.04
 - Ruff Plugin version [e.g. 0.0.19 ]

**Additional context**

**Comment by koxudaxi** [comment]
Sorry for the late confirmation.
The latest version seems to have resolved the issue, so I will close it.
