### ISSUE TITLE
Support for `ruff format`

### ISSUE THREAD

**Issue by urob** [koxudaxi/ruff-pycharm-plugin#257]
As of v0.0.287, the `ruff` formatter is now in alpha state ([format readme](https://github.com/astral-sh/ruff/blob/charlie/formatter/crates/ruff_python_formatter/README.md)). The VS Code extensions already supports it as experimental feature. It would be great if it could be supported as experimental feature in the PyCharm extension as well.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/koxudaxi/ruff-pycharm-plugin/issues/257">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/koxudaxi/ruff-pycharm-plugin/issues/257/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/koxudaxi/ruff-pycharm-plugin/issues/257/pledge.svg">
</picture>
</a>

**Comment by koxudaxi** [comment]
@urob 
The `v0.0.22` supports `ruff format` as an option.
please check the config panel.

Thank you very much!!

**Comment by urob** [comment]
> @urob 
> 
> The `v0.0.22` supports `ruff format` as an option.
> 
> please check the config panel.
> 
> 
> 
> Thank you very much!!
> 
> 
> 
Fantastic, thanks so much!
