### ISSUE TITLE
"ruff format" reformats the entire file with the "reformat code" action 

### ISSUE THREAD

**Issue by fnep** [koxudaxi/ruff-pycharm-plugin#281]
**Describe the bug**
When "use ruff format" is enabled and only a portion of the code is selected, the "reformat code" action reformats the entire file instead of only the selected code.

**To Reproduce**
1. Enable "use ruff format"
2. Select only a few lines of a larger file
3. Run Edit -> Reformat Code
4. The whole file is reformatted instead

**Expected behavior**
Only the selected code should be reformatted.

**Environments (please complete the following information):**
 - IDE: PyCharm Professional 2023.2.2
 - OS: macOS 14.0 (23A344) 
 - Ruff Version: 0.0.291
 - Plugin version: 0.0.23

**Comment by fnep** [comment]
Very cool, thank you for fixing this  😊

**Comment by koxudaxi** [comment]
@fnep 
I have released the fixed version as `0.0.29`
Thank you for your patience.

**Comment by bookin** [comment]
Do nothing (default IDE action, looks like) with selected code in the PyCharm 2023.3.2 (Professional Edition)
