### ISSUE TITLE
Add support for EAP 233

### ISSUE THREAD

**Issue by elliotwaite** [koxudaxi/ruff-pycharm-plugin#283]
**Is your feature request related to a problem? Please describe.**
I am unable to use this plugin with PyCharm 2023.3 EAP.

**Describe the solution you'd like**
I'm not familiar with Gradle, but it looks like changing `pluginUntilBuild = 232.*` to `pluginUntilBuild = 233.*` might fix this. I'm not sure if anything else needs to be changed as well.

P.S. Thanks for making this plugin!

**Comment by koxudaxi** [comment]
@elliotwaite 
`0.0.24` supports EAP 2023.3
Thank you !!

**Comment by elliotwaite** [comment]
@koxudaxi Thanks! It's working.
