### ISSUE TITLE
error: unexpected argument '--format' found

### ISSUE THREAD

**Issue by grundew** [koxudaxi/ruff-pycharm-plugin#295]
I get the following error when ruff is triggered with save file

caused by: The following command was executed:

C:\Users\gw\venv311\Scripts\ruff.exe --exit-zero --no-cache --force-exclude --no-fix --format json --stdin-filename sb_mictest/test_hw/mic_test/test_mic_membrane_disable.py -

The exit code: 2
The error output of the command:

error: unexpected argument '--format' found

  tip: to pass '--format' as a value, use '-- --format'

Usage: ruff.exe check <FILES|--fix|--no-fix|--unsafe-fixes|--no-unsafe-fixes|--show-source|--no-show-source|--show-fixes|--no-show-fixes|--diff|--watch|--fix-only|--no-fix-only|--ignore-noqa|--output-format <OUTPUT_FORMAT>|--output-file <OUTPUT_FILE>|--target-version <TARGET_VERSION>|--preview|--no-preview|--config <CONFIG>|--select <RULE_CODE>|--ignore <RULE_CODE>|--extend-select <RULE_CODE>|--extend-ignore <RULE_CODE>|--per-file-ignores <PER_FILE_IGNORES>|--extend-per-file-ignores <EXTEND_PER_FILE_IGNORES>|--exclude <FILE_PATTERN>|--extend-exclude <FILE_PATTERN>|--fixable <RULE_CODE>|--unfixable <RULE_CODE>|--extend-fixable <RULE_CODE>|--extend-unfixable <RULE_CODE>|--respect-gitignore|--no-respect-gitignore|--force-exclude|--no-force-exclude|--line-length <LINE_LENGTH>|--dummy-variable-rgx <DUMMY_VARIABLE_RGX>|--no-cache|--isolated|--cache-dir <CACHE_DIR>|--stdin-filename <STDIN_FILENAME>|--exit-zero|--exit-non-zero-on-fix|--statistics|--add-noqa|--show-files|--show-settings|--ecosystem-ci>

For more information, try '--help'.

Error Running Ruff
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:241)
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:180)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:319)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:57)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:22)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	... 37 more

python 3.11
ruff 0.1.2

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
I will check it tonight.

**Comment by owendaw** [comment]
it looks like --format has been replaced with --output-format in ruff 0.1.0 @koxudaxi 

See Breaking Changes: https://github.com/astral-sh/ruff/blob/fe9727ac38db6d3b8ab3efcbf4e1766eb2ec9736/BREAKING_CHANGES.md

For now you can downgrade your version of ruff. Version prior to format change is 0.0.292 @grundew

**Comment by koxudaxi** [comment]
@owendaw 
I had applied the changes.
https://github.com/koxudaxi/ruff-pycharm-plugin/pull/268
It works in my environment.

Could you please show us your environment?
I tried to test in Windows too. I couldn't reproduce the error.

The plugin changes the execution argument by ruff version.
https://github.com/koxudaxi/ruff-pycharm-plugin/blob/aa7f1cd68863b1eb44e4ed38916fc7a57bc5a538/src/com/koxudaxi/ruff/RuffVersion.kt#L14-L18
I guess the plugin can't detect the ruff version sometimes.

**Comment by owendaw** [comment]
I see. I have done a dive of the code and have an idea of what may be going on.

I am running on MacOS Sonoma 14.1
I have python 3.12 installed with pyenv
ruff==0.1.5

I believe that the issue may actually be permissions related, with respect to the system's ruff executable. 

I am able to reproduce this error when my Pycharm python interpreter is set to my system interpreter. 
I am able to resolve this error when creating a virtual environment and installing the latest version of ruff there.

Looking into the permissions, it appears that the system interpreter puts an additional xattr permission "com.apple.provenance" on ruff, that is not present in the virtual environment.

It would make sense that 
https://github.com/koxudaxi/ruff-pycharm-plugin/blob/aa7f1cd68863b1eb44e4ed38916fc7a57bc5a538/src/com/koxudaxi/ruff/Ruff.kt#L84
is ending up at the "else" as there would be an issue setting the version.

I hope this is helpful @koxudaxi

**Comment by koxudaxi** [comment]
@owendaw 
Thank you for investigating the issue.
I have created the PR. 
I will test the new version before releasing it!!
