### ISSUE TITLE
Live config reload

### ISSUE THREAD

**Issue by gurland** [koxudaxi/ruff-pycharm-plugin#296]
**Is your feature request related to a problem? Please describe.**
I think the live update of the configurations on change would simplify overall configuration of ruff.

**Describe the solution you'd like**
I want the plugin to be able to track changes to a `.ruff.toml` file (or any other supported file) and restart ruff-lsp. 

**Describe alternatives you've considered**
Currently I just restart PyCharm to update any changes.

**Additional context**
I use Pycharm 2023.2

**Comment by koxudaxi** [comment]
Thank you for requesting the feature.
We can watch the changes in specific files.
But, I don't know if we can restart lsp server without restarting PyCharm.
I will take time to investigate.

**Comment by skewty** [comment]
Please also ensure `pyproject.toml` is watched as that is where many (most?) projects stick their ruff config.

**Comment by koxudaxi** [comment]
I have created the issue for the feature request. I can't find the feature in the PyCharm.
https://youtrack.jetbrains.com/issue/IDEA-339730/Request-the-addition-of-LSP-server-restart-functionality

**Comment by koxudaxi** [comment]
@gurland 
I found a mistake that I didn't think about `.ruff.toml` :sweat: 
I will fix the next release.

**Comment by koxudaxi** [comment]
@gurland
I released the fixed version as `v0.0.28`

**Comment by gurland** [comment]
@koxudaxi thank you for the dedication!
