### ISSUE TITLE
Many rule violations do not appear in inspections

### ISSUE THREAD

**Issue by gmyers18** [koxudaxi/ruff-pycharm-plugin#299]
For a simple ruff.toml config and a trivial Python script, a number of rule violations that are indicated by `ruff check` do not appear as inspections results in PyCharm.

## Config / Code
**ruff.toml**
```toml
select = ["ALL"]
ignore = ["ANN", "D", "EM"]

[lint]
preview = true
```

**foo.py** (screenshot to show line numbers, raw source code is attached)
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/26069899/178ddb7d-af99-4a59-b109-81e56d78c06e)

## Results
As shown below `ruff check` reports 12 errors, whereas the plugin only reports 4 (plus some other issues raised by builtin PyCharm inspections).  The rules missed by the plugin are: `CPY001`, `TD002`, `TD003`, `FIX002`, `W293`, `COM812`, `W292`.  This is a bare-bones example and I don't expect that this is a comprehensive list of rules that do not appear in the inspection results.

I've tried a number of configurations tweaks, but none have made a difference.  Also, I can't seem to discern any sort of pattern as far as which rules show up in the inspections, and which do not.  

**ruff check**
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/26069899/a1dce10d-dff4-41b8-be5b-9d7a45525932)

**Plugin**
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/26069899/7f9ca2b9-5a9d-4911-bebe-7e31ed4de732)

## Environment
 - IDE: PyCharm Community 2023.2.3
 - OS: Windows 10 22H2 19045.3570
 - Python: 3.11.6
 - Ruff Version: 0.1.3
 - Plugin version: 0.0.24
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/26069899/ade7a672-ca94-4e43-afea-e2159fca92eb)

[ruff.toml.txt](https://github.com/koxudaxi/ruff-pycharm-plugin/files/13206334/ruff.toml.txt)
[foo.py.txt](https://github.com/koxudaxi/ruff-pycharm-plugin/files/13206335/foo.py.txt)
[bar.py.txt](https://github.com/koxudaxi/ruff-pycharm-plugin/files/13206336/bar.py.txt)

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
It's interesting. the inspection feature might not get some of the results of ruff warning 🤔 
I will check it.
