### ISSUE TITLE
The caret moves after ruff format when save on file

### ISSUE THREAD

**Issue by grundew** [koxudaxi/ruff-pycharm-plugin#330]
**Describe the bug**
When ruff format is enabled and ruff is set to run on save, the whole file seems to be reloaded by pycharm and the caret ends up in a different place than before (further down in the document).

**To Reproduce**
1. Enable ruff format
2. Enable run ruff when the python file is saved
3. Make a change in a python file and save
4. See the cursors jumps lower than in the document (the file should fill more than screen height)

**Expected behavior**
The cursor should be at the same place before and after ruff has been run

**Environments (please complete the following information):**
 - IDE: [Pycharm pro 2023.3]
 - OS: [Windows 11]
 - Ruff Version [0.1.7 ]
 - Plugin version [0.0.27 ]

**Comment by koxudaxi** [comment]
@grundew 
I'm sorry for my late reply.
I think we meet [the same issue](https://github.com/koxudaxi/ruff-pycharm-plugin/issues/312)
We should fix it.
Thank you!!

**Comment by koxudaxi** [comment]
@grundew 
I have released the fixed version `0.0.29` . 
Thank you very much!!

**Comment by KotlinIsland** [comment]
I am using 0.0.30 and still observing this defective behaviour, I'll raise a new issue
