### ISSUE TITLE
Bad path forming for ruff config file on WSL

### ISSUE THREAD

**Issue by FieryDruid** [koxudaxi/ruff-pycharm-plugin#358]
**Describe the bug**

My project is located in a directory inside WSL. Ruff is installed there as well. When I specify the path to ruff.toml through pycharm, a relative path from wsl is inserted in the “Ruff config file” field, which leads to an error when forming a full path to the config file.

The solution to the problem is manual editing of `ruff.xml` in `.idea/`. If only “ruff.toml” is left in the path, the path to it will be formed correctly.

**To Reproduce**
1. Create project in wsl directory
2. install ruff on wsl
3. create config file in root project directory
4. Open this directory in PyCharm from Windows

**Expected behavior**
A correct parsing of the path to the config file or the ability to specify a relative path

**Screenshots**

Ruff executable and ruff config file settings:
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/36041629/131c4a44-f70f-4246-ab55-823016b065da)

Error: 
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/36041629/629ab681-e4e8-478a-b7ed-6ec6a38b8d78)

**Environments (please complete the following information):**
 - IDE: `PyCharm Professional 2023.3.2`
 - OS: `Windows 10 + WSL (Ubuntu 22.04)`
 - Ruff Version: `0.1.9`
 - Plugin version: `0.0.29`

**Comment by koxudaxi** [comment]
OK, I will fix it.
