### ISSUE TITLE
Ruff does not run in new python project

### ISSUE THREAD

**Issue by gshipilov** [koxudaxi/ruff-pycharm-plugin#36]
**Describe the bug**
Ruff fails to run on save or code reformat with message `Cannot find the project associated with this Ruff environment`. No additional information is provided by the plugin. It looks like the plugin expects some kind of configuration file to be present? But I couldn't find any docs to that effect.

Ruff runs perfectly fine on its own in the terminal.

**To Reproduce**
1. Create a new blank PyCharm project (File -> New Project -> Pure Python).
2. Install ruff and the pycharm plugin.
3. Run ruff by saving the default file, triggering a reformat, or cmd-shift-a action.

**Expected behavior**
Ruff should run!

**Screenshots**
<img width="1503" alt="Screenshot 2022-12-24 at 11 34 23 AM" src="https://user-images.githubusercontent.com/80237201/209444432-7091c1cb-db39-43a4-8203-dfc9c5dfe375.png">

**Environments (please complete the following information):**
 - IDE: PyCharm Pro 2022.3
 - OS: macOS 13.0.1
 - Ruff Version 0.0.192
 - Plugin version 0.0.3

**Additional context**

**Comment by koxudaxi** [comment]
@gshipilov
Thank you for creating the issue.
I can't reproduce the error :thinking: 

> It looks like the plugin expects some kind of configuration file to be present? But I couldn't find any docs to that effect.

We don't need additional settings.
The error happened because the plugin couldn't find the current project path.
The error is not related to installing `ruff`.

Could you provide additional information on Python interpreter and virtualenv?

Also, do you meet the error in any project? Or, only a new project?

**Comment by wgordon17** [comment]
@koxudaxi FWIW, I'm hitting this as well. This is a pyenv environment running on MacOS

```bash
$ which ruff
/Users/wgordon17/.pyenv/shims/ruff
```

<img width="699" alt="image" src="https://user-images.githubusercontent.com/22222756/210190471-a97a7a39-4521-404c-9138-3e518c090855.png">

**Comment by koxudaxi** [comment]
@wgordon17 
Thank you for the comment.
I will check it on mac :bow:

**Comment by qarkai** [comment]
Same here on Arch Linux with system-wide `ruff`.

**Comment by koxudaxi** [comment]
I have released the new version as `v0.0.5`
Thank you very much!!

**Comment by qarkai** [comment]
Have same issue if ruff is installed via pip in user directory, i.e. in ~/.local/bin/ruff

**Comment by koxudaxi** [comment]
@qarkai 
I have released the new version `0.0.7`
the version finds `ruff` in `~/.local/bin/`

**Comment by qarkai** [comment]
@koxudaxi Already tested, issue is gone, thanks!
