### ISSUE TITLE
(🐞) the 'Project Specific > ruff executable' field isn't saveable

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#379]

**Comment by koxudaxi** [comment]
we should fix it in the PR 
https://github.com/koxudaxi/ruff-pycharm-plugin/pull/381

**Comment by koxudaxi** [comment]
@KotlinIsland 
Can we delete the executable path in a config file?
I think we don't need to save the path in the file.
The plugin can find the ruff executable from active Python SDK.
Otherwise, the global ruff path works for the remaining use cases.

**Comment by KotlinIsland** [comment]
sounds perfect
