### ISSUE TITLE
Not compatible with Pycharm 2024.1 EAP

### ISSUE THREAD

**Issue by alexgmin** [koxudaxi/ruff-pycharm-plugin#383]
**Screenshots**
![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/8340441/cabb9767-d074-449a-bb88-b2c982943e96)
Since 0.0.29 is also not compatible it refuses to update it.

I did some tests by editing the version compatibility of the plugin in my local and the "Run ruff" action with the format enabled works.

**Environments (please complete the following information):**
 - IDE: Pycharm profesional 2024.1 EAP 6
 - Plugin version 0.0.28

**Comment by washeck** [comment]
I believe this was fixed in https://github.com/koxudaxi/ruff-pycharm-plugin/commit/4dbe03c28c92bcbd71ffc2a9a6fd9901d0591de7 but it is not released yet.

@koxudaxi Would you please issue a new release? This is blocking me from using EAP versions which I like to test. Thanks

**Comment by koxudaxi** [comment]
@washeck 

OK, I will release it today.

Background:
I met the unittest error in another plugin, CI/CD, when it uses the latest EAP version for the unittest.
Last weekend, I spend time to debug the error.
But I can't fix it yet :(
It works fine as a plugin.
https://github.com/koxudaxi/pydantic-pycharm-plugin/actions/runs/7994205495/job/21879373618
