### ISSUE TITLE
ruff 0.3.0 and plugin 0.0.30

### ISSUE THREAD

**Issue by hkokko** [koxudaxi/ruff-pycharm-plugin#392]
**Describe the bug**
I cannot find how to run ruff in the plugin in PyCharm 2023.3.4 on Mac OS very latest official one on Mac Studio M2 Max

For example during the save of a python file (when ruff plugin has been configured to format on save) nothing happens. 

Using PyCharm action run ruff -> nothing happens. 

I CAN run in PyCharm terminal commands like ruff check and it produces a list of warnings. 

Created a clean virtual environment in Pycharm with installing python 3.11 in Venv with all the libraries I use and then installed ruff  from normal project interpreted list 

I also see no tooltips with ruff info happening. 

Config is here
<img width="1439" alt="2024-03-01_14-35-50" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/2825397/3eb29915-409f-4269-9c05-09f3fb8ae3c3">

**Comment by koxudaxi** [comment]
@hkokko 
Sorry for the late reply.
Was this triggered by something?
Did you upgrade your macOS version, or did you give it a ruff version, etc.?

**Comment by koxudaxi** [comment]
I've tried running it using Pycharm 2023.3.5 on macOS 14.0 on M1.
The ruff plugin is 0.0.31.
The version of ruff is 0.3.4

It is difficult to provide a m2 max mac, can you provide any other information?

**Comment by koxudaxi** [comment]
I hope the problem has been resolved in `v0.0.32`
If you will meet the problem, then please leave a comment.
https://github.com/koxudaxi/ruff-pycharm-plugin/pull/409
