### ISSUE TITLE
Support for new integrated ruff language server

### ISSUE THREAD

**Issue by raayu83** [koxudaxi/ruff-pycharm-plugin#447]
**Is your feature request related to a problem? Please describe.**
Currently this plugin uses ruff-lsp, which has been superseded by the integrated ruff lsp server the day before yesterday, see https://astral.sh/blog/ruff-v0.4.5

**Describe the solution you'd like**
Would be great if this plugin supported the new integrated server.

**Additional context**
Thanks for providing this really useful plugin!

**Comment by Mogost** [comment]
@koxudaxi First of all, thanks for the awesome plugin!
How big changes to the plugin are needed for this?
Can we expect a new version soon?

**Comment by koxudaxi** [comment]
Thank you for creating the issue.
I expected to release the PR https://github.com/koxudaxi/ruff-pycharm-plugin/pull/437 to support the LSP for the non-pro version of the IDE before picking up this PR.
But we have to wait for the release of the next LSP4IJ version.

OK, I will support the new integrated ruff lsp first.

**Comment by koxudaxi** [comment]
@raayu83 
I'm sorry for my late action.
You can install the plugin from the page.

https://github.com/koxudaxi/ruff-pycharm-plugin/releases/tag/v0.0.34

**Comment by koxudaxi** [comment]
@raayu83 
The new version has a new option to enable `ruff server`

new option:
<img width="841" alt="image" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/630670/03cd394e-d0fd-4781-a8f7-e7ccd0e006e6">



Full screen:
<img width="1223" alt="image" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/630670/05696953-c53c-45af-a51c-73ab414181f0">

you can check the `ruff server`  in the process list after open the your project.
```bash
ps ax |grep "ruff server"
 7039   ??  S      0:00.07 /Users/koudai/PycharmProjects/pythonProject1/.venv/bin/ruff server --preview
20806   ??  S      0:00.01 /Users/koudai/PycharmProjects/pythonProject1/.venv/bin/ruff server --preview
20857 s008  S+     0:00.00 grep ruff server

```

<img width="496" alt="image" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/630670/1842ca5a-27a2-4a64-823e-de93645756ee">
