### ISSUE TITLE
PyCharm EAP Support

### ISSUE THREAD

**Issue by joostecg** [koxudaxi/ruff-pycharm-plugin#449]
**Describe the bug**
With each release of and EAP on PyCharm Professional the plugin fails to load or is incompatible with the latest EAP

**To Reproduce**
1. Go to 'Settings/Plugins'
2. Click on 'Ruff'
3. See error " Incompatible: requires IDE build 241.* or earlier"

**Expected behavior**
Continued use with latest EAP unless some reason exists that would break the compatibility.

**Environments (please complete the following information):**
 - IDE: [PyCharm Professional; 2024.2 EAP]
 - OS: [Windows 11]
 - Ruff Version [0.0.33]
 - Plugin version [0.0.33 ]

**Comment by washeck** [comment]
@koxudaxi I know you are busy with porting to the new LSP integration. Anyway, would you be so kind to just rebuild the current version with updated `until-build` so we can use the current version of the plugin in PyCharm EAP. Thank you very much.

**Comment by koxudaxi** [comment]
Sorry for the slow response.
I have tried, but I can't build it properly just by increasing the version. Some APIs cannot be referenced, so something needs to be fixed.

https://github.com/koxudaxi/ruff-pycharm-plugin/actions/runs/9585184135/job/26430490957?pr=461

**Comment by koxudaxi** [comment]
We have to upgrade the intellijPlatform plugin  to v2
But, the latest bata don't support EAP :(
https://github.com/JetBrains/intellij-platform-gradle-plugin/issues/1629

**Comment by joostecg** [comment]
Thanks a million, looks like it is resolved now
