### ISSUE TITLE
Ruff server option sets `--preview`, causing all preview rules to be enabled

### ISSUE THREAD

**Issue by simonpercivall** [koxudaxi/ruff-pycharm-plugin#471]
**Describe the bug**
As part of enabling the new `ruff server` LSP integration to work in https://github.com/koxudaxi/ruff-pycharm-plugin/pull/454, the `--preview` flag was added.

More than just enabling the new LSP integration, this also seems to enable all preview rules (if the project, as I have, uses `lint.select = ["ALL"]` with selective ignores).

Now that `ruff server` is out of preview (since Ruff 0.5.3), the `--preview` option can be removed.

**To Reproduce**
1. Enable `Use ruff server`
2. Enable "ALL" rules

**Expected behavior**
Preview rules should not be enabled by the plugin (unless asked for, if such an option existed).

**Comment by Olegt0rr** [comment]
Since plugin calls `--preview`, it conflicts with direct ruff calls :(

Example: https://github.com/astral-sh/ruff/issues/12591

**Comment by simonpercivall** [comment]
Workaround for now: [explicit-preview-rules](https://docs.astral.sh/ruff/preview/#selecting-single-preview-rules)

**Comment by Olegt0rr** [comment]
> Workaround for now: [explicit-preview-rules](https://docs.astral.sh/ruff/preview/#selecting-single-preview-rules)

It enables preview in ruff, but I still can't disable it in plugin

**Comment by koxudaxi** [comment]
The  supported version was released 
[0.0.36](https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/597308)

Thank you
