### ISSUE TITLE
Ruff Plugin v0.0.36 needs lps4ij to be installed

### ISSUE THREAD

**Issue by Shuricks2015** [koxudaxi/ruff-pycharm-plugin#490]
**Describe the bug**
The plugin does not work out of the box anymore. It states that it requires lsp4ij to be installed (screenshot).

**To Reproduce**
Update Ruff Plugin from version 0.0.35 to version 0.0.36

**Expected behavior**
Ruff only needs the requested lsp4ij if the Option to use it is set.

**Screenshots**
![RuffPluginError](https://github.com/user-attachments/assets/93a24d87-b403-4262-94fa-82b04fe9a36f)

**Environments (please complete the following information):**
 - IDE: IntelliJ IDEA Ultimate 2024.2.1
 - OS: Windows 10
 - Ruff Version: 0.6.2
 - Plugin version: 0.0.36

**Additional context**
Either the dependency should be installed when I update/install or it should be failing when I select to use LSP4IJ.

**Comment by adamJLev** [comment]
Having this issue too, and it would be ok if everything worked as is but when installing lsp4j my python 
autocompletion stops working completely.
I had to downgrade the Ruff plugin to the previous version manually to get things working again

**Comment by kamilos956** [comment]
> Having this issue too, and it would be ok if everything worked as is but when installing lsp4j my python autocompletion stops working completely. I had to downgrade the Ruff plugin to the previous version manually to get things working again

same here, completely doesn't work

**Comment by johnthagen** [comment]
Would it be possible to make LSP4IJ an optional dependency?

**Comment by koxudaxi** [comment]
Thank you for reporting it.
The latest version has been made private to avoid confusion.
I assumed LSP4IJ would be installed automatically, but it seems I have to install it myself.

@johnthagen 
This may not be a problem at present, but in the future we would like to make it lsp-only to keep pace with astral.

**Comment by angelozerr** [comment]
> Having this issue too, and it would be ok if everything worked as is but when installing lsp4j my python 
> autocompletion stops working completely.
> I had to downgrade the Ruff plugin to the previous version manually to get things working again

Is it working with LSP from Jetbrains? If yes could create an issue please in LSP4IJ repo by explaining in detail how to reproduce the problem.

**Comment by koxudaxi** [comment]
@angelozerr 
Please let me know if I'm missing something.
When using LSP4IJ from a plugin, the LSP4IJ plugin needs to be installed, right?
Is it possible to include this in the dependencies or make it easy to install?
Do new users always need to install LSP4IJ from the marketplace themselves?
Would you like me to provide any thoughts or information about these questions regarding LSP4IJ and plugin dependencies?

**Comment by angelozerr** [comment]
> @angelozerr 
> Please let me know if I'm missing something.
> When using LSP4IJ from a plugin, the LSP4IJ plugin needs to be installed, right?

Yes LSP4IJ is a plugin not a library.

> Is it possible to include this in the dependencies or make it easy to install?
> Do new users always need to install LSP4IJ from the marketplace themselves?
> Would you like me to provide any thoughts or information about these questions regarding LSP4IJ and plugin dependencies?

I am sorry I dont master thIis topic. @fbricon have you some idea?

**Comment by koxudaxi** [comment]
@angelozerr @fbricon
Could you distribute the plugin as library too?
I don't know you can publish a plugin and a library from same source code.
But, I can't find the benefit to install lsp4is as standalone plugin.

**Comment by angelozerr** [comment]
> @angelozerr @fbricon
> Could you distribute the plugin as library too?
> I don't know you can publish a plugin and a library from same source code technically .
> But, I can't find the benefit to install lsp4is as standalone plugin. 

We publish LSP4IJ as plugin because it provides some UI component like LSP console and you can enjoy with LSP without developping a plugin.

I dont know if it is possible to provide library and plugin both. And if we can provide it, plugin and library should work together.

I fear that it will not be easy to do.

Please create an issue.

**Comment by angelozerr** [comment]
> The plugin does not work out of the box anymore. It states that it requires lsp4ij to be installed

I think this behavior is not a bug. You upgrade a plugin which requires a new plugin dependency so is it normal to have this popup which suggests to install the new required plugin, no,?

If you have never installed ruff plugin it should install lsp4ij out of the box I think, no?

**Comment by Shuricks2015** [comment]
@angelozerr If you state it as such I agree with you that you should get this error message. 

But my issue is that lsp4ij is not a necessary part of the plugin. 
For example I use the plugin without the server option because the server indexes all subdirectories on startup, which my companies security software doesn't like at all and shoots up the CPU usage to 100% for ~15min. 

I see that lsp4ij has the benefit to be able to use the server option of ruff for the Community Edition, as the integrated LSP support is Pro-versions only. 
I would suggest to have checks on the config options if they can be enabled, like the lsp options for community edition has to have lsp4ij installed.

But that is just my personal opinion and I don't know if it's possible that way.

**Comment by angelozerr** [comment]
> @angelozerr If you state it as such I agree with you that you should get this error message. 
> 
> But my issue is that lsp4ij is not a necessary part of the plugin. 

OK I understand now after reading your comment. I think @koxudaxi  is working on that with https://github.com/koxudaxi/ruff-pycharm-plugin/pull/494

> For example I use the plugin without the server option because the server indexes all subdirectories on startup, which my companies security software doesn't like at all and shoots up the CPU usage to 100% for ~15min. 
> 

That is too bad, but I think it is an issue with ruf language server, right @koxudaxi ?

> I see that lsp4ij has the benefit to be able to use the server option of ruff for the Community Edition, as the integrated LSP support is Pro-versions only. 

Yes but I wonder if you have the same problem sith LSP from Jetbrains. Is your IDE is freezing when you open completion or Is completion return nothing and avoid showing completion result from PyCharm?

> I would suggest to have checks on the config options if they can be enabled, like the lsp options for community edition has to have lsp4ij installed.
> 
> But that is just my personal opinion and I don't know if it's possible that way.

I think https://github.com/koxudaxi/ruff-pycharm-plugin/pull/494 does that

**Comment by Shuricks2015** [comment]
> OK I understand now after reading your comment. I think @koxudaxi is working on that with https://github.com/koxudaxi/ruff-pycharm-plugin/pull/494

This is a problem the ruff language server has with my companies security program. This is not something that can or should be attempted to fix in the scope of this plugin. 

> Yes but I wonder if you have the same problem sith LSP from Jetbrains. Is your IDE is freezing when you open completion or Is completion return nothing and avoid showing completion result from PyCharm?

I don't understand what you mean by this question. I can use the ruff server version with IntelliJ Ultimate, after the indexing step of the server that is horribly slow for me the server works great and the feedback is way faster than without the lsp. 

Then I hope #494 fixes this as an optional dependency as I think it is a very good thing for the Community editions.

**Comment by angelozerr** [comment]
> > OK I understand now after reading your comment. I think @koxudaxi is working on that with https://github.com/koxudaxi/ruff-pycharm-plugin/pull/494
> 
> This is a problem the ruff language server has with my companies security program. This is not something that can or should be attempted to fix in the scope of this plugin. 

Perhaps you should report this problem to the ruff language server project?

> 
> > Yes but I wonder if you have the same problem sith LSP from Jetbrains. Is your IDE is freezing when you open completion or Is completion return nothing and avoid showing completion result from PyCharm?
> 
> I don't understand what you mean by this question. I can use the ruff server version with IntelliJ Ultimate, after the indexing step of the server that is horribly slow for me the server works great and the feedback is way faster than without the lsp. 

This ruff ij plugin provides the capability to select the LSP support, from JetBrains or from LSP4IJ,  but perhaps I am wrong and in this case sorry for the noise.

> 
> Then I hope #494 fixes this as an optional dependency as I think it is a very good thing for the Community editions.
> 
>
