### ISSUE TITLE
Would you develop  a  uv  plugin for pycharm   ,  ask      entreatly . 

### ISSUE THREAD

**Issue by Super1Windcloud** [koxudaxi/ruff-pycharm-plugin#509]
Would you develop  a  uv  plugin for pycharm   ,  ask      entreatly .

**Comment by dhruvmanila** [comment]
They're going to natively support uv, refer https://youtrack.jetbrains.com/issue/PY-75985/Allow-extending-PythonAddNewEnvironmentPanel#focus=Comments-27-10763817.0-0 and the tracking issue is https://youtrack.jetbrains.com/issue/PY-70533.

**Comment by koxudaxi** [comment]
@dhruvmanila 
Good new for everyone!!
I appreciate your help!
