### ISSUE TITLE
Reformat code doesn't work

### ISSUE THREAD

**Issue by stallam-unb** [koxudaxi/ruff-pycharm-plugin#512]
**Describe the bug**
Ctrl+Alt+L no longer appears to format code since update 0.0.40. Running `ruff format` in a terminal however does work as intended.

**To Reproduce**
1. Open any file.
2. Press Ctrl+Alt+L.
3. Only default PyCharm stuff works.

**Expected behavior**
Ruff should auto format code.

**Screenshots**
**Environments (please complete the following information):**
 - IDE: PyCharm 2024.2.2
 - OS: Windows 11
 - Ruff Version `ruff 0.6.7`
 - Plugin version `0.0.40`

**Comment by nickymarino** [comment]
This might be the same problem as #424 -- I was able to follow the [advice there](https://github.com/koxudaxi/ruff-pycharm-plugin/issues/424#issuecomment-2134286719) to enable "Use ruff format(Experimental) for version 0.0.289 or later" in PyCharm Settings > Tools > Ruff, and that fixed this problem for me

**Comment by stallam-unb** [comment]
> This might be the same problem as #424 -- I was able to follow the [advice there](https://github.com/koxudaxi/ruff-pycharm-plugin/issues/424#issuecomment-2134286719) to enable "Use ruff format(Experimental) for version 0.0.289 or later" in PyCharm Settings > Tools > Ruff, and that fixed this problem for me

It is already enabled for me and it still doesn't work.

**Comment by fadhely** [comment]
Since PyCharm 2024.2 multiple Ruff commands do not work anymore.
Such as $ruff check folderName/ --select I --fix and so on...

**Comment by gromsterus** [comment]
I have a similar problem.
1. Code example
![image](https://github.com/user-attachments/assets/60581180-61f8-44ad-b1c4-628acb95ede1)

2. Do `Reformat Code` (`ruff check --fix` worked well, but `ruff format` did not)
![image](https://github.com/user-attachments/assets/eb79439e-9c45-4b45-9472-7927e18b7af9)

3. If I do `File -> Reload All From Disk`
![image](https://github.com/user-attachments/assets/b03f21f7-b16f-4ec7-82c6-72bdc3526412)

IDE: PyCharm 2024.2.3 (Professional Edition)
OS: macOS
Ruff Version: 0.6.9
Plugin version: 0.0.40

Plugin settings
![image](https://github.com/user-attachments/assets/f47a2647-ac3e-4005-b6fb-794a79a70ca1)

**Comment by fadhely** [comment]
Does it work if you uncheck `Enable Ruff LSP feature` ?

**Comment by gromsterus** [comment]
@fadhely no, it doesn't work :(

**Comment by stallam-unb** [comment]
It seems like @koxudaxi released v0.0.41 recently, and now seems to has fixed the issue for me. Thanks!

I will close the issue now, but if anyone else in this thread still has this problem, let me know and I will reopen the issue.

**Comment by koxudaxi** [comment]
@stallam-unb 
Yes, Thank you for creating and closing this issue.
I removed the broken version from the store. but I didn't check the issue. sorry.
