### ISSUE TITLE
Incosistent behaviour w/ CLI: `per-file-ignores` not being used

### ISSUE THREAD

**Issue by ManuelAlvarezC** [koxudaxi/ruff-pycharm-plugin#56]
**Describe the bug**

Pycharm warns me of errors I have explicitly ignored usign the `ruff.toml` file and that are ignored by the CLI.

**To Reproduce**
1. Create a `ruff.toml` file with the following contents:
 ```
line-length = 120
select = ["ALL"]
ignore = ["ANN101", "ANN102"]
fix=false

show-source = true

[pydocstyle]
convention = "google"

[per-file-ignores]
"tests/*.py" = ["S101", "ANN001","ANN101", "ANN102", "ANN201", "D100", "D101"]
```

This should:
- Apply all linters, except `["ANN101", "ANN102"]` to all files
- Apply all linters except  `["S101", "ANN001","ANN101", "ANN102", "ANN201", "D100", "D101"]` to the files in the `tests` folders
    * Concretely, the `D100` and `D101` should make that don't require docstrings at the module and class levels.

2. Create a dummy file `tests/example.py` with the following content:
```python
class DummyTest:
    
    def test_i_dont_want_type_hints(self):
        """Here I explain what the test do."""

```
3. Run the following:
```
$ ruff tests/examples.py
# No errors are returned
```

4. Check on Pycharm and see the following:
![image](https://user-images.githubusercontent.com/13135380/213522944-3d26dcb7-663b-4358-ae9b-4738a32b09d3.png)
![image](https://user-images.githubusercontent.com/13135380/213523226-11ea2c60-b9ef-4682-80df-41f331092cce.png)

**Expected behavior**
I will expect the pycharm plugin to:
- Be consistent with the CLI behaviour
- Ignore files and rules that I have configured it to ignore

**Screenshots**
Already provided in the step 5.

**Environments**
 - IDE: PyCharm 2022.3.1 (Professional Edition) (Build #PY-223.8214.51, built on December 20, 2022)
 - OS: Ubuntu 22.04.1 LTS
 - Ruff Version: 0.0.225
 - Plugin version: 0.0.5

**Additional context**
Not important for this case, but while checking at the plugin configuration I come accross this typo on `Settings > Editor > Inspections > Python > Ruff inspeciton` ( It should read inspection)
![image](https://user-images.githubusercontent.com/13135380/213525057-abb21a36-135b-4689-a64b-266c60d03fcc.png)

**Comment by ManuelAlvarezC** [comment]
Thank you so much, it works like a charm

**Comment by henribru** [comment]
Unfortunately this still doesn't seem to work if your ruff config isn't in the root directory of your project. Maybe there should be a setting for configuring the config file path? Although I'm noticing that when using the ruff CLI it seems to be able to pick up my config regardless of the working directory, so maybe it's possible to piggyback off of that

**Comment by koxudaxi** [comment]
@henribru 
Thank you for your comment.
> Although I'm noticing that when using the ruff CLI it seems to be able to pick up my config regardless of the working directory, so maybe it's possible to piggyback off of that

Did you mention the option?

```bash
ruff check --help | grep "\-\-config"
      --config <CONFIG>  Path to the `pyproject.toml` or `ruff.toml` file to use for configuration
```

**Comment by henribru** [comment]
> @henribru Thank you for your comment.
> 
> > Although I'm noticing that when using the ruff CLI it seems to be able to pick up my config regardless of the working directory, so maybe it's possible to piggyback off of that
> 
> Did you mention the option?
> 
> ```shell
> ruff check --help | grep "\-\-config"
>       --config <CONFIG>  Path to the `pyproject.toml` or `ruff.toml` file to use for configuration
> ```

No, when I tested with the CLI I didn't use that option. According to https://github.com/charliermarsh/ruff#pyprojecttoml-discovery the Ruff CLI automatically finds the closest config file for each file when no config path is specified, I guess that's why it works

**Comment by koxudaxi** [comment]
The latest plugin adds the option :thinking: 
![image](https://user-images.githubusercontent.com/630670/219434331-3514e4ec-bbc7-4f51-9ec7-a55bad817410.png)

**Comment by koxudaxi** [comment]
@henribru
Can you show me your project file tree structure?
I can't reproduce the problem on my local machine.

**Comment by koxudaxi** [comment]
> Unfortunately this still doesn't seem to work if your ruff config isn't in the root directory of your project. 

It works for me. 🤔 
pyproejct.toml is for only Poetry in the example.

<img width="1800" alt="image" src="https://user-images.githubusercontent.com/630670/219537753-e201867f-bfe7-43ad-8ab4-345b441362f7.png">

**Comment by henribru** [comment]
@koxudaxi In my project I'm using `pyproject.toml` for the Ruff config, but `pyproject.toml` isn't in the project directory, it's in a first-level subdirectory. It would be like moving `main.py`and `pyproject.toml` inside `root` in your example screenshot and removing `ruff.toml` and putting that config inside `pyproject.toml` instead.

**Comment by koxudaxi** [comment]
@henribru 
Thank you for explaining your situation.
I try to reproduce your project.
It works fine with ruff `0.0.246` and the plugin `v0.0.8`
![Screenshot from 2023-02-18 00-15-40](https://user-images.githubusercontent.com/630670/219693357-74791c9b-b879-4a6a-870d-10ec8c2d66e8.png)
![Screenshot from 2023-02-18 00-18-09](https://user-images.githubusercontent.com/630670/219693684-419d7bb8-a25d-4cb5-a883-1b35727f3118.png)

**Comment by henribru** [comment]
@koxudaxi I was planning to make a reproduction repo, but when trying the latest version now it seems to work fine actually. Not sure what change fixed it, but thanks!
