### ISSUE TITLE
Include code in error message pop-up

### ISSUE THREAD

**Issue by ljnsn** [koxudaxi/ruff-pycharm-plugin#58]
**Is your feature request related to a problem? Please describe.**
Would it be possible to add the error code to the message shown when hovering over the code? For example, in the below screenshot to see "F401 `datetime` imported but unused" (the same way ruff cli also reports it).

![image](https://user-images.githubusercontent.com/82611987/213893412-0942224a-94eb-46b1-a408-387f20c34c17.png)

**Describe the solution you'd like**
Include the error code with the message. This could be turned on/off via a config option.

**Comment by koxudaxi** [comment]
@ljnsn 
Thank you for creating the issue.
The new version `v0.0.6` has been released.
