### ISSUE TITLE
Cannot find Ruff

### ISSUE THREAD

**Issue by DanK96** [koxudaxi/ruff-pycharm-plugin#70]
**Describe the bug**
Getting 'Error Running Ruff' (screenshot below) when trying to run the Ruff-action

**To Reproduce**
1. Click on 'Search Everywhere'
2. Select 'Run Ruff'

**Screenshots**
![image](https://user-images.githubusercontent.com/23012221/217358418-ddcbcc18-d84e-421a-985a-3f50202d9b8f.png)

**Environments (please complete the following information):**
 - IDE: PyCharm 2022.3.2 (Professional Edition)
 - OS: Windows 11 22H2
 - Ruff Version: 0.0.243
 - Plugin version: 0.0.6

**Additional context**
Probably I'm just doing something wrong. But when trying to run Ruff via terminal it works without a problem and I have no idea what else to try, so any help would be appreciated.

**Comment by m-entrup** [comment]
I have the same problem on Windows 10.
Ruff is installed globally (with pipx) and in the venv that my PyCharm project is using. Running `ruff` in the system terminal and in the PyCharm terminal works fine, but the Ruff plugin shows "Cannot find Ruff".

`runRuff()` seems to be the function that outputs this error message.
https://github.com/koxudaxi/ruff-pycharm-plugin/blob/bc6f304af7e0fe9114984f6950fb18c2da006da7/src/com/koxudaxi/ruff/Ruff.kt#L106

**Comment by koxudaxi** [comment]
@DanK96 @m-entrup 
Thank you for the reports.
I will install ruff and PyCharm for test in my Windows 11 tonight.

**Comment by koxudaxi** [comment]
@DanK96 @m-entrup 
I have released the new version `0.0.7`.
The version find `ruff.exe` when the system is windows.
