### ISSUE TITLE
Cannot find Ruff

### ISSUE THREAD

**Issue by gdementen** [koxudaxi/ruff-pycharm-plugin#82]
**Describe the bug**
Ruff plugin "Cannot find Ruff" (error window with that message)

**To Reproduce**
* Configure plugin to "Run ruff when the python file is saved"
* Save a file

**Expected behavior**
Ruff being run

**Environments (please complete the following information):**
 - IDE: PyCharm 2022.3.2 (Community Edition)
 - OS: Windows 10
 - Ruff Version: 0.0.239 or 0.0.244
 - Plugin version: 0.0.6

**Additional context**
I am using conda environments and ruff is installed in my development environment for that project (and works fine on the command-line when that environment is activated). Would it be possible that your plugin does not support conda environments?
I do not think this is relevant, but since ruff is not available in anaconda yet, I install it via pip in my conda environment.

**Comment by koxudaxi** [comment]
@gdementen 
Thank you for creating the issue.
Have you tried `0.0.7` which is support Windows and user sites?
Unfotually, I have not used conda environment yet.
Can you share the path of your ruff path?

**Comment by gdementen** [comment]
Sorry I didn't see the closed issue. I haven't not tried yet the new version, I don't think it was available when I tried. I will try that hopefully next week.

**Comment by gdementen** [comment]
The path of ruff on my installation is IIRC: `c:\[somewhere]\Miniconda3\envs\dev310\Scripts\ruff.exe`

**Comment by gdementen** [comment]
I just tried here at home and the new version does not seem to make a difference for me.

I also tried to install ruff in the base conda environment but it does not seem to work either.

I think the easiest fix would be to let the user configure the path explicitly (ideally would still autodetect when left blank for those users where that works).

**Comment by koxudaxi** [comment]
I will check how to get conda path in PyCharm.

> I think the easiest fix would be to let the user configure the path explicitly (ideally would still autodetect when left blank for those users where that works).

Great idea. I will think the way.

Thank you very much.

**Comment by gdementen** [comment]
FWIW, I just tested the version 0.9. It still does not autodetect ruff in my project environment, but the global path settings works very nicely. Thanks for the nice plugin and quick reaction !
